apiVersion: v1
kind: ConfigMap
metadata:
  name: babelbot-configuration
  labels:
    {{- include "babelbot.labels" . | nindent 4}}
data:
  TargetLanguageCode: {{ .Values.babelbot.deepL.targetLanguageCode }}
  OnlyReactToAllowedUsers: {{ .Values.babelbot.telegram.onlyReactToAllowedUsers | quote }}
