apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "babelbot.fullname" . }}
  labels:
    {{- include "babelbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "babelbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "babelbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "babelbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DeepL__AuthKey
              valueFrom:
                secretKeyRef:
                  name: babelbot-configuration
                  key: DeepLAuthKey
            - name: DeepL__DefaultTargetLanguageCode
              valueFrom:
                configMapKeyRef:
                  name: babelbot-configuration
                  key: TargetLanguageCode
            - name: Telegram__ApiKey
              valueFrom:
                secretKeyRef:
                  name: babelbot-configuration
                  key: TelegramApiKey
            {{- range $index, $_ := .Values.babelbot.telegram.allowedUsers }}
            - name: Telegram__AllowedUsers__{{ $index | add1 }}
              valueFrom:
                secretKeyRef:
                  name: babelbot-configuration
                  key: TelegramAllowedUsers{{ $index | add1 }}
            - name: Telegram__OnlyReactToAllowedUsers
              valueFrom:
                configMapKeyRef:
                  name: babelbot-configuration
                  key: OnlyReactToAllowedUsers
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
