apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: babelbot-configuration
  labels:
    {{- include "babelbot.labels" . | nindent 4}}
data:
  TelegramApiKey: {{ .Values.babelbot.telegram.apiKey | b64enc }}
  {{- range $index, $userId := .Values.babelbot.telegram.allowedUsers }}
  TelegramAllowedUsers{{ $index | add1 }}: {{ $userId | b64enc }}
  {{- end }}
  DeepLAuthKey: {{ .Values.babelbot.deepL.authKey | b64enc }}
